export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "#F5F1EA",
        "canvas-warm": "#EFE7DC",
        surface: "#FFFDFC",
        "surface-raised": "#FFFFFF",
        "surface-tinted": "#F8F3EE",
        "surface-inverse": "#24191A",
        "text-primary": "#24191A",
        "text-secondary": "#5C4B4C",
        "text-muted": "#8A7778",
        "text-inverse": "#F8F4EF",
        "border-subtle": "#E6D8CF",
        "border-strong": "#CBB7A9",
        divider: "#DCCDC2",
        "brand-primary": "#6E1F32",
        "brand-primary-hover": "#5D192A",
        "brand-primary-active": "#4D1422",
        "brand-primary-soft": "#F4E5EA",
        "brand-secondary": "#A36A2C",
        "brand-secondary-soft": "#F6E9D7",
        "accent-olive": "#5E6B3F",
        "accent-olive-soft": "#EAF0DF",
        "accent-plum": "#4D3B57",
        "accent-plum-soft": "#EEE8F2",
        success: "#2E7D5B",
        "success-soft": "#E4F3EC",
        warning: "#A86C1F",
        "warning-soft": "#F8EBD9",
        danger: "#B13E3E",
        "danger-soft": "#F9E3E3",
        info: "#355C7D",
        "info-soft": "#E3EDF5",
        focus: "#8C2F46",
      },
      fontFamily: {
        display: '"Cormorant Garamond", "Times New Roman", serif',
        body: '"Manrope", "Avenir Next", "Segoe UI", sans-serif',
        mono: '"IBM Plex Mono", "SFMono-Regular", monospace',
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "1.02", fontWeight: "600", letterSpacing: "-0.03em" }],
        "display-lg": ["52px", { lineHeight: "1.04", fontWeight: "600", letterSpacing: "-0.025em" }],
        "heading-xl": ["40px", { lineHeight: "1.08", fontWeight: "600", letterSpacing: "-0.02em" }],
        "heading-lg": ["32px", { lineHeight: "1.12", fontWeight: "600", letterSpacing: "-0.015em" }],
        "heading-md": ["26px", { lineHeight: "1.18", fontWeight: "600", letterSpacing: "-0.01em" }],
        "heading-sm": ["22px", { lineHeight: "1.22", fontWeight: "600", letterSpacing: "-0.005em" }],
        "title": ["18px", { lineHeight: "1.3", fontWeight: "600", letterSpacing: "-0.01em" }],
        "body-lg": ["18px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        "label": ["12px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.08em" }],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
      },
      borderRadius: {
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "20px",
        xl: "28px",
        full: "999px",
      },
      boxShadow: {
        sm: "0 6px 18px rgba(36, 25, 26, 0.08)",
        md: "0 14px 34px rgba(36, 25, 26, 0.12)",
        lg: "0 24px 60px rgba(36, 25, 26, 0.18)",
        inner: "inset 0 1px 0 rgba(255, 255, 255, 0.45)",
      },
      borderColor: {
        DEFAULT: "#E6D8CF",
      },
    },
  },
  plugins: [],
}
