// Mock data for cellars
export const mockCellars = [
  {
    id: '1',
    name: 'Bordeaux Reserve',
    region: 'Bordeaux, France',
    bottleCount: 24,
    createdAt: '2023-05-12',
    description: 'Fine Left Bank selections',
  },
  {
    id: '2',
    name: 'Burgundy Selection',
    region: 'Burgundy, France',
    bottleCount: 18,
    createdAt: '2023-08-20',
    description: 'Small grower Pinot Noirs and Chardonnays',
  },
  {
    id: '3',
    name: 'Italian Treasures',
    region: 'Tuscany, Italy',
    bottleCount: 32,
    createdAt: '2024-01-15',
    description: 'Tuscan and Piedmont classics',
  },
];

// Mock data for bottles - keyed by cellar ID
export const mockBottles = {
  '1': [
    {
      id: 'b1',
      name: 'Château Lafite Rothschild',
      vintage: 2015,
      region: 'Pauillac',
      type: 'Red Wine',
      grapes: 'Cabernet Sauvignon, Merlot',
      alcohol: '12.5%',
      notes: 'Classic Left Bank elegance',
      position: 'A1',
    },
    {
      id: 'b2',
      name: 'Château Margaux',
      vintage: 2016,
      region: 'Margaux',
      type: 'Red Wine',
      grapes: 'Cabernet Sauvignon, Merlot, Petit Verdot',
      alcohol: '12.8%',
      notes: 'Elegant and refined',
      position: 'A2',
    },
    {
      id: 'b3',
      name: 'Pichon Lalande',
      vintage: 2018,
      region: 'Pauillac',
      type: 'Red Wine',
      grapes: 'Cabernet Sauvignon, Merlot',
      alcohol: '13.2%',
      notes: 'Approachable and lovely',
      position: 'A3',
    },
  ],
  '2': [
    {
      id: 'b4',
      name: 'Domaine de la Romanée-Conti',
      vintage: 2017,
      region: 'Vosne-Romanée',
      type: 'Red Wine',
      grapes: 'Pinot Noir',
      alcohol: '13.0%',
      notes: 'Legendary Burgundy',
      position: 'B1',
    },
    {
      id: 'b5',
      name: 'Chablis Grand Cru',
      vintage: 2019,
      region: 'Chablis',
      type: 'White Wine',
      grapes: 'Chardonnay',
      alcohol: '12.5%',
      notes: 'Crisp and mineral',
      position: 'B2',
    },
  ],
  '3': [
    {
      id: 'b6',
      name: 'Brunello di Montalcino',
      vintage: 2016,
      region: 'Montalcino',
      type: 'Red Wine',
      grapes: 'Sangiovese Grosso',
      alcohol: '14.0%',
      notes: 'Complex and structured',
      position: 'C1',
    },
    {
      id: 'b7',
      name: 'Barolo',
      vintage: 2017,
      region: 'Piedmont',
      type: 'Red Wine',
      grapes: 'Nebbiolo',
      alcohol: '14.5%',
      notes: 'Powerful and elegant',
      position: 'C2',
    },
    {
      id: 'b8',
      name: 'Moscato d\'Asti',
      vintage: 2022,
      region: 'Piedmont',
      type: 'White Wine',
      grapes: 'Moscato Bianco',
      alcohol: '5.5%',
      notes: 'Sweet and sparkling',
      position: 'C3',
    },
  ],
};
